"""add best_time_to_visit to destinations

Revision ID: 7fb64b29f2f4
Revises: c854fa432e86
Create Date: 2026-07-11 20:23:10.508727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb64b29f2f4'
down_revision: Union[str, Sequence[str], None] = 'c854fa432e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinations', sa.Column('best_time_to_visit', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('destinations', 'best_time_to_visit')
    # ### end Alembic commands ###
